wheel_width: 0.018           # Width of wheels (m)
wheel_radius: 0.060          # Radius of wheel (m)
wheel_base: 0.160            # Distance between wheel centers (m)
chassis_length: 0.200        # Length of main chassis link (m)
chassis_thickness: 0.070     # Thickness of plate that forms chassis (m)
wheel_mass: 10.00            # Mass of wheel (kg)
chassis_mass: 1.00           # Mass of chassis (kg)
caster_mass: 1.00            # Mass of ball casters (kg)